### ISSUE TITLE
Security Q - API/WAF

### ISSUE THREAD

**Issue by bsaurusrex** [amazon-connect/amazon-connect-chat-ui-examples#153]
Should a WAF be implemented in front of the API gateway for self-hosted?

https://github.com/amazon-connect/amazon-connect-chat-interface/blob/master/.github/docs/CustomChatAndWidgetSelfHostedSetup.md#customized-widget-and-chat-interface-ui-self-hosted

**Comment by RayShonami** [comment]
@bsaurusrex Yes. 

The apigateway doesn't prevent attacks from multiple users abusing the system from sending too many requests. And you probably want to prevent certain regions from accessing the chat. So, having a WAF would resolve those security concerns. 

Also, if you want to, you could require a security token to be provided to the apigateway; so that only authorized users can access it.

**Comment by bsaurusrex** [comment]
I recommend adding optional WAF into the diagram and docs to communicate best practices.

**Comment by spenlep-amzn** [comment]
Hi @bsaurusrex,

As @RayShonami mentioned, it is best practice to add security to the API Gateway. This sample code does not come with any built in security to avoid being opinionated.

I have raised a pull request to update the documentation.

![](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/513d80fdc845bcf091657428dfdc05614270c338/cloudformationTemplates/startChatContactAPI/images/StartChatContactArchitecture.png?raw=true)

Linking some useful pages:
- https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-aws-waf.html
- https://wellarchitectedlabs.com/

Going to resolve, thank you for raising this concern.
-Spencer
