### ISSUE TITLE
Issues with disconnect after chatSession.endChat

### ISSUE THREAD

**Issue by adelatanca99** [amazon-connect/amazon-connect-chat-ui-examples#154]
Having issues with the self-hosted widget from Amazon Connect. 

After disconnect (chatSession.endChat) the new script behind scenes (amazon-connect-chat-interface.js) is making another API call which fails, getting 403 Access denied.
<img width="749" alt="Screenshot 2023-11-02 at 17 07 39" src="https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/95678533/64b302ae-e031-48a2-8b6b-738afdbd1404">
Using an old script (2-3 years old) after disconnect that API call to event isn't made.
<img width="919" alt="image" src="https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/95678533/ad54200e-9bd6-4c89-91b8-bece9a789723">

Does anyone know why the new script is behaving like this?

**Comment by chaumdh** [comment]
Hi [adelatanca99](https://github.com/adelatanca99), the new behavior is because we added read/delivery receipts feature last year. This is a known bug that happens when a chat ends before the read/delivery events get a chance to fully propagate. We have a back log task to clean up this bug but it should not affect any chat functionality. Please reach out if you have any other questions.

**Comment by spenlep-amzn** [comment]
Hi @adelatanca99,

Team has released ChatJS fix to address this issue. Please use latest version: `npm install amazon-connect-chatjs@~2.2.2`

I have generated a bundle file from ChatInterface/master if you need to use it:
https://github.com/amazon-connect/amazon-connect-chat-interface/blob/spenlep/bundle-file-latest-chatjs/amazon-connect-chat-interface.js

Resolving issue
-Spencer
