### ISSUE TITLE
Select chat tab event

### ISSUE THREAD

**Issue by RyukaTagasaki** [amazon-connect/amazon-connect-chat-ui-examples#2]
When integrate the UI to my own web app.
How can i check which chat tab is selected and who i am talking to in my own code?
(i mean which contact id)
How can i catch the event when agent switch to another chat tab?

**Comment by mschersten** [comment]
+1 on this.  For voice calls, we show different information to the agents about the call.  This is kind of trivial for voice calls, because they only handle one at a time, and we just show new information when a new call starts.  But with multiple chats being handled at once, it's essential that the agent see the full context that we can show them specific to the chat they are handling at the time.

One workaround I can imagine would be to listen for the "typing" events, and use that as a proxy for which chat is being handled at the time, but this is later than we really want to know about it.

Short of implementing a full CCP API, just using postMessage() to communicate about some CCP events would be helpful, and we could create our own listeners for that.

**Comment by vovanb** [comment]
+1 - don't understand why it is closed?
