### ISSUE TITLE
initiateChat failure2

### ISSUE THREAD

**Issue by iamgokul46** [amazon-connect/amazon-connect-chat-ui-examples#20]
I am trying to customize the default demo website and start the chat from customized website. I have changed the form, added few styles when i click on startchat . The website starts loading but it doesn't initiate chat. In inspect console it is "initiateChat failure2" error.

**Comment by efh365** [comment]
This typically happens due to the backend thinking that the previous chat is still active. This happens in one of two scenarios:

1) You end a chat and then try to start a new one within a few seconds. 
   This happens because the DDB marks a chat as active until the chat transcript is dumped in S3. This takes about 30 seconds to happen so there is a delay in when the chat is marked as complete. You can update your solution to instead mark the chat as completed as a response to the chat ended event

2) You are never able to start a new chat after starting your first one.
    This is probably due to the S3 trigger not being configured properly. If the S3 trigger from the chat transcript bucket is misconfigured, there is never an event generated that updates the DDB saying that the chat has completed. As a result the frontend is always pulling an expired chat.
