### ISSUE TITLE
The widget stucked at loading status

### ISSUE THREAD

**Issue by andykuek** [amazon-connect/amazon-connect-chat-ui-examples#22]
Hi I have checked that all the details are correct in the troubleshooting section . However the widget remains in loading status.  Any help to resolve this is really appreciated!

Thks

**Comment by efh365** [comment]
Can you please add any debugging information? does it happen for every chat or only chats when you use the same name? did you launch your stack with uuids instead of arns? any errors in the logs?

**Comment by robmoores** [comment]
I don't know of it's any help but I have also experienced this on several occasions - the spinner just keeps spinning! It happens when I edit the index.html file Save As a new version, upload it to S3 and change the reference on Cloudformation. I've assumed it's because I've hacked away at the code and done something wrong but think this unlikely as e.g. it happened when I put an extra line in in below the h1 .... Opened in incognito window etc  ... Happy to test etc under guidance ...

**Comment by khastation** [comment]
@robmoores can you help provide with your browser console logs so that we could try to analyze the issue?

**Comment by robmoores** [comment]
> @robmoores can you help provide with your browser console logs so that we could try to analyze the issue?

Thanks and yes I can. Can you please be very specific about exactly what logs you want? I'm learning fast but detailed direction will help :-) Thanks

**Comment by efh365** [comment]
@robmoores this will be difficult for us to help you debug if you have made a number of modifications to the code. Can you try to redeploy the stack in a clean environment and then let us know if you experience the issue there. If you don't, then it is a problem with modifications you have made and we won't be able to help with that.

**Comment by robmoores** [comment]
Hi efh365. Thank you for replying. I have this issue whether I have modified the index.html or not. I can do a new install again and upload the browser logs - but as above I would need detailed guidance on how to find and send these logs :-)

**Comment by efh365** [comment]
can you look at these two closed issues to see if they fix your problem and then let me know the results from those debugging steps?
https://github.com/amazon-connect/amazon-connect-chat-ui-examples/issues/20
https://github.com/amazon-connect/amazon-connect-chat-ui-examples/issues/29

**Comment by robmoores** [comment]
Hi efh. Many thanks for replying. I will have to look at these tomorrow eve (UK time) now!

**Comment by robmoores** [comment]
Hi. Apologies for slow reply - we have been trying to investigate this for many days !
I have looked at #20 and #29 and I dont think they are related to the issue we are having. 
Sometimes the UI works fine - then it goes crazy and adds thousands of entries into the /logs file and at the same time the wheel is spinning endlessly ...!
I have found this in the Cloudwatch logs(my xxxxxx added):
AccessDeniedException: User:
arn:aws:sts::1xxxxxxxxxxx3:assumed-role/amazon-connect-b56d2ae769-InitiateChatLambdaExecut-EW9Q3LTWARNW/amazon-connect-b56d2ae769e4-web-InitiateChatLambda-KIZZT9MM8B3S
is not authorized to perform: connect:StartChatContact on resource:
arn:aws:connect:us-east-1:1xxxxxxxxxxx3:instance/d2a484f2-1760-4363-8a3c-e6a2ee802176/contact-flow/808685f0-8456-4578-babe-7c6080c652ca

I wondered if this access issue causes the endess log wrotes - but maybe they are not related. I cannot see where these log files are written .

**Comment by robmoores** [comment]
Re issue #20: the first case you mention could;l be part of the issue:
Can you please let me know how we can identify the chat ended event ?
Thanks

You end a chat and then try to start a new one within a few seconds.
This happens because the DDB marks a chat as active until the chat transcript is dumped in S3. This takes about 30 seconds to happen so there is a delay in when the chat is marked as complete. You can update your solution to instead mark the chat as completed as a response to the chat ended event

**Comment by lukeschmidt-wisc** [comment]
@robmoores what would " You can update your solution to instead mark the chat as completed as a response to the chat ended event" look like
        chatSession.onChatDisconnected(function (data) {
             data._updateContactStatus("ended");
        });

Overall we are getting the same error as Re issue #24 but we think setting it to complete will resolve the issue. We are using amazon-connect-chat-interface.js in our project and implementing the asyncCustomerChat-UX.  Thanks for the help and the discussions.

**Comment by lukeschmidt-wisc** [comment]
chatSession.onChatDisconnected(function (data) {
**data._updateContactStatus("ended");**
});

 .data._updateContactStatus is not a function is what we are getting when we use the snippet above.  what object do we need to access the updateContactStatus and then change the object.  Thanks for the help!
![image](https://user-images.githubusercontent.com/74072411/100783605-9b352700-33d3-11eb-95fa-d967469a0789.png)

**Comment by robmoores** [comment]
@lukeschmidt-wisc I think that the advice given in use case 1 in issue #20 is to update DDB. So I think when you get to here in the index.html:
        chatSession.onChatDisconnected(function (data) {
            resetForm();       <--- as well as reset the form, call a Lambda to update the row in DDB to mark it as closed 
        });

Thoughts ?

**Comment by lukeschmidt-wisc** [comment]
We are attempting to keep the lambda functions to a minimum with our project and would rather use javascript.  When you say "call a Lambda to update the row in **DDB to mark it as closed**" are you referring to the table created by the cloudformationtemplate named like:  asyncCustomerChat-UX-chatContactDataTable....?  If so what column would be marked with the value closed?

**Comment by robmoores** [comment]
@lukeschmidt-wisc You can wrap the javascript code in a lambda function, then you can trigger it from the API Gateway as the other two Lambdas are already. My understanding from reading the code is that is you put any value other than "NONE" in the S3Key it will effectively treat it as closed. BUT ... I am still a novice so please consider that and do your testing :-)

**Comment by mukundparmar** [comment]
is this working for anybody, I am stuck at the same issue. 

chatSession.onChatDisconnected(function (data) {
data._updateContactStatus("ended");
});

Above code didn't work for me in fact after updating that and also removed resetForm() and now it's not even reloading the page second time.

**Comment by MattDN93** [comment]
Another note on this - I've seen endless loads when the `StartChatContact` API ends up returning [ParticipantToken](https://docs.aws.amazon.com/connect/latest/APIReference/API_StartChatContact.html#API_StartChatContact_ResponseSyntax) for a chat whose session is no longer active leading to the 403 in the logs. I looked into my deployment and noticed that when this exact behaviour occurs it's when `userDisplayHash` is the same:
* you enter "John" as the first name and "matt" as username and init a new chat
* DDB gets a new item where `userDisplayHash` is "mattJohn" and `nextContactId` is "CURRENT_CHAT"
* End the chat, and quickly start a new one with the same first name "John" and "matt" username
* This then fetches the stale "mattJohn" chat by `userDisplayHash` and since the column `nextContactId` is still CURRENT_CHAT, it errors as the ParticipantToken returned from DDB is no longer valid

In this case, a quick fix is to set `nextContactId` for that `userDisplayHash` as something other than CURRENT_CHAT and the solution will init a new chat session.

**Comment by efh365** [comment]
I just wanted to check in here - is there still an issue or has it been resolved?

**Comment by robmoores** [comment]
Hi @efh365 . As per comment on Nov 23rd we decided to take the easy way out and not write to the log - that resolves the issue. I'vve not reconsidered it for a whilebut happy to do some testing under guidance :-)
