### ISSUE TITLE
Source Code for amazon-connect-chat-interface.js

### ISSUE THREAD

**Issue by amicming** [amazon-connect/amazon-connect-chat-ui-examples#47]
Hello Team, 

Is there a way we can get a code for amazon-connect-chat-interface.js? Currently, we have a minified code. Any idea when it will go to open source?

Thanks,

**Comment by cmrockwell** [comment]
I agree with and second this request. Source for `amazon-connect-chat-interface.js` seems like a big omission. Especially in the way it's setting CSS style in the JS; only thing to do is overwrite it with more specific styles. Also API docs would be nice for ChatInterface would be nice, because ChatInterface is not part of the amazon-connect-chatjs API

**Comment by cmrockwell** [comment]
The fact that devs won't respond is a concern. What kind of data mining and analytics happens in this code?

**Comment by khastation** [comment]
@amicming @cmrockwell Thanks for your request, we’re currently looking into it and will get back shortly.

**Comment by efh365** [comment]
We have now open sourced chat interface js. You can find the repo here: https://github.com/amazon-connect/amazon-connect-chat-interface
