### ISSUE TITLE
Clicking on URL Preview opens link in same web page, so losing the chat

### ISSUE THREAD

**Issue by robmoores** [amazon-connect/amazon-connect-chat-ui-examples#53]
Hi. I am successfully displaying a URL preview in a chat window on the Amazon Connect Omni-Channel Demo web page that comes with the URL Preview Cloudformation stack. However if I click on the preview it opens the link in the same tab, and I lose the chat - even if I click on the back button on the browser. I can right click on the link and open it in a new tab but I can't really expect the customer to do that.

Is there a way that I can configure the page or the chat UI or the response so that the link opens in a new tab or window and the chat can continue ?

(Just in case it is relevant ... In this specific case I am opening a web landing page that then uses javascript to automatically launch a Facebook login app in a popup, which, on successful login closes and the landing page then redirects the user to a web site in the same tab).

Thanks.

**Comment by MHamza8070** [comment]
Hi man! did you managed to get this done, i need guidance!

**Comment by spencerlepine** [comment]
Hi @robmoores, the team is currently maintaining URL Preview example code but not actively working on feature requests.

Team has recently released changes that automatically apply `target=_blank` attribute to urls sent in the chat. 

<img width="1396" alt="Screenshot 2023-07-07 at 12 33 03 PM" src="https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/60903378/b7a176e8-8150-4c67-b749-7d4e9c531b7e">

If the use case requires further customization, a custom chat interface can be built by forking https://github.com/amazon-connect/amazon-connect-chat-interface and generating a new UI bundle file: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/urlPreviewForAsyncChat/website/js

Resolving this issue due to inactivity. Team is not planning to release updates to urlPreview example.

Thanks,
Spencer
