### ISSUE TITLE
ConnectParticipant is not a constructor

### ISSUE THREAD

**Issue by ashokdevlabs** [amazon-connect/amazon-connect-chat-ui-examples#56]
Trying to connect connectParticipant service using aws-sdk but it giving error like below.

TypeError: aws_sdk__WEBPACK_IMPORTED_MODULE_5___default.a.ConnectParticipant is not a constructor

Please find the sample request below.
var params = {
          ParticipantToken: ParticipantToken,  // ParticipateToken from StartContactChat response
          Type: [ 
            "WEBSOCKET","CONNECTION_CREDENTIALS"
          ]
   };

var connectparticipant = new AWS.ConnectParticipant({apiVersion: '2018-09-07'});

        connectparticipant.createParticipantConnection(params, function(err, data) {
          if (err) console.log(err, err.stack); 
          else     console.log(data); 
        });

Could anyone help me with an example to resolve this issue.

**Comment by ashokdevlabs** [comment]
@tscheuneman Could you please suggest a fix for this

**Comment by mcosicaws** [comment]
Could you please confirm that version of the AWS SDK you are importing has the ConnectParticipant service included?

It would be helpful if you could provide more details on your architecture, like are you trying to `createParticipantConnection` on client side, by importing AWS SDK? 

It might be easier to use https://github.com/amazon-connect/amazon-connect-chatjs as it already has everything you need. You can find more details in README, including the order in which you'd need to import dependencies.

Thanks,
Milos

**Comment by ashokdevlabs** [comment]
@mcosicaws  I am using AWS SDK version 2.932.0 and using the below code to connect to Amazon Connect service.
 
import AWS from 'aws-sdk';
import 'amazon-connect-streams';
import 'amazon-connect-chatjs';

 AWS.config.update({
    region: "us-east-1",
    accessKeyId: "accessKeyId",
    secretAccessKey: "secretAccessKey"
  });

  useEffect(()=>{
    var connect = new AWS.Connect({apiVersion:'2017-08-08'});

    var initiateChatRequest = {
      ParticipantDetails: {
        DisplayName: "Customer"
      },
      ContactFlowId: "ContactFlowId",
      InstanceId: "InstanceId",      
      Attributes:{
        customerName:"customerName"
      }
    };

    connect.startChatContact(initiateChatRequest, function(err, data) {
      if (err) console.log(err, err.stack);
      else     {
        console.log(data);
        //setInitialChatResponse(data);
        var params = {
          ParticipantToken: data.ParticipantToken, 
          Type: [ 
            "WEBSOCKET","CONNECTION_CREDENTIALS"
          ]
        };

        var connectparticipant = new AWS.ConnectParticipant({apiVersion: '2018-09-07'});

        connectparticipant.createParticipantConnection(params, function(err, data) {
          if (err) console.log(err, err.stack); 
          else     console.log(data); 
        });
      }
    });
  },[]);

Please let me know if i am missing anything.

**Comment by mcosicaws** [comment]
Thanks for sharing the details, much appreciated. 

In case you're developing a customer side chat (i.e. a widget on your public website), you don't need to import `amazon-connect-streams`, since that library lets you embed the agent side UI (Contact Control Panel (CCP)) into your page.

Also, `connect.startChatContact` is typically invoked from 'server' side, for instance, you'd create a Lambda function that invokes `connect.startChatContact`, and since AWS Lambda already includes AWS SDK, you would simply do something like this:
```javascript
const ConnectClient = require('aws-sdk/clients/connect');
const Connect = new ConnectClient();
...
const startChatResult = await Connect.startChatContact(params).promise()
```

You would create an API Gateway endpoint, which you'd invoke from the client side, API Gateway would then invoke the Lambda function, and the function would return `startChatResult` back to your client. 

Once you get the `startChatResult` back to your client, you could then simply use `amazon-connect-chatjs` to create a ChatSession.  Please check https://github.com/amazon-connect/amazon-connect-chatjs#api
In this case, you don't need to import AWS SDK on your client side. In case you need AWS SDK for other purposes (invoking another AWS Service), please make sure you import packages in the correct order, as described in https://github.com/amazon-connect/amazon-connect-chatjs#scenario-4-chatjs-only-with-aws-sdk-import
*Import ChatJS before the AWS SDK, and ensure the AWS SDK version you are using contains the ConnectParticipant Service.*

`amazon-connect-chatjs` is helpful when you want to build your own Chat UI, however you could use `amazon-connect-chat-interface` (which uses `amazon-connect-chatjs`) in case you want a pre-built Chat UI, which you could embed to your website, and customize according to your website look and feel. 

Thanks,
Milos

**Comment by mcosicaws** [comment]
Closing due to no response, please feel free to re-open should you need any additional help.
