### ISSUE TITLE
when i refresh or switch's tab the custom chat widget, the chat disappeared instead of continue the previous ongoing chat.

### ISSUE THREAD

**Issue by MHamza8070** [amazon-connect/amazon-connect-chat-ui-examples#58]
when i refresh the custom chat widget, the chat starts again instead of continue the previous ongoing chat and on agent side, previous chat not ended. So I need guidance about how to handle refresh scenario in chat widget, I run this repository code, it also not entertains the refresh thing. Can you guys please guide i will be very thankful to you!

**Comment by mcosicaws** [comment]
Could you please confirm you if have deployed asyncCustomerChatUX: 
https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/asyncCustomerChatUX

That solution enables customers to continue an existing chat interaction. 
First time a chat contact is started, Lambda function invokes Amazon Connect StartChatContact API, and stores the result in a DynamoDB table. In case customer comes back (or refreshes the browser) and starts a chat contact, the Lambda function checks DynamoDB table to see whether there is an existing chat open for that user. If so, the current chat is returned to the website instead of starting a new one. This enables your user to pick up the existing chat where they left off on any device.

The chat widget doesn't automatically pop up, it rather requires user to click on the chat icon/button. In case you wanted chat widget to pop up automatically, you would need a mechanism that would, on page loaded, check if there was an ongoing chat session, and if that was the case, pop up chat widget and start chat contact automatically.
