### ISSUE TITLE
Cannot start new chats without refreshing the webpage

### ISSUE THREAD

**Issue by kevinjfogarty** [amazon-connect/amazon-connect-chat-ui-examples#63]
After having deployed the ASync solution as well as cloning/building the customChatWidget, I am able to start a chat without issue, but am not able to consistently start a 2nd chat after the 1st has ended (clicking end chat from widget) without refreshing the webpage.

I am using a unique name/username in the form each time, but subsequent chats after the first has ended seem to be working on the backend (the console shows messages being sent/received) but those messages never render in the widget.  After refreshing the webpage, a new chat starts as expected.

**Working**
![working](https://user-images.githubusercontent.com/47748348/157711538-3bc2ac8f-f922-4374-8694-5d6ba711b059.png)

**Not Working**
![not_working](https://user-images.githubusercontent.com/47748348/157711660-ad7c3697-4994-4ed1-bb8e-56e936db808e.png)

One thing I'm noticing is that there is another "t" top-level React Component being instantiated each subsequent time a new chat is started.  When looking at the source code for the amazon-connect-chat-interface.js file, I found that the "t" component is the minimized name for the BrowserRouter Component.   Sometimes the issue presents itself on the 2nd attempt (2 t components), sometimes it takes a couple more tries (as in the screenshot).  I'm not sure if having multiple "t" components is part of the issue or not, but thought it was worth mentioning.

**Comment by agnel0410** [comment]
Hi Kevin,

Did you manage to resolve this issue ?

**Comment by kevinjfogarty** [comment]
No, not exactly. We instead went with the widget from the async chat
solution (instead of the custom chat widget) which did not have this issue.

**Comment by fidel-tensoriot** [comment]
Also ran into this issue using the custom chat solution.

**Comment by angieyu** [comment]
Please use the async chat solution. We've been seeing problems with custom chat.

**Comment by coronel08** [comment]
@angieyu is this the async chat you are recommending?  https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/asyncCustomerChatUX

I unfortunately had to alter the following libraries for a project because we needed a fully customized widget and chat-interface. I would build my `Amazon-Connect-Chat-Interface` and drag and replace that file in my `CustomChatWidget`s public folder I believe the file i replaced is called `amazon-connect-interface.js`

The libraries I altered are below
- The Amazon-Connect-Chat-Interface: https://github.com/amazon-connect/amazon-connect-chat-interface
- The Custom Chat Widget: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/customChatWidget

I believe that this problem goes all the way down to the library used by all these resources. The following library https://github.com/amazon-connect/amazon-connect-chatjs 
we can see an open ticket here for the problem. https://github.com/amazon-connect/amazon-connect-chatjs/issues/88 

I'm able to sometimes connect to a 2nd, 3rd, even 4th chat but the more times I connect to a chat without refreshing my window (sometimes it fails on the 2nd chat), the higher the chances of an empty transcript and unresponsive chat interface/chat transcript. I believe it has to do with the `amazon-connect-chatjs` sending multiple connections AND then trying to connect to the chat and retrieve the transcripts. On 1st connection its not a problem at all, but once we get to a 3rd connection or higher there is a higher chance of the chat not working until we refresh.

**Comment by mhiaror** [comment]
Can you share a codesandbox or link to reproduce the issue. 

After changing `apiGateway`, `contactFlowId` and `instanceId` in [index.html](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/master/customChatWidget/public/index.html), and I am able to start chats(start first chat -> end chat -> start second chat -> end chat -> start third chat) without refreshing the page.

Also, if you have created a test instance; Can you share your `apiGateway`, `contactFlowId` and `instanceId` so I can reproduce the issue ?

**Comment by xiajohn** [comment]
Closing due to no response for more than 2 months. Please open new issue if the issue is still there
