### ISSUE TITLE
customChatWidget double call issue After Agent Misses Call

### ISSUE THREAD

**Issue by komnatadeveloper** [amazon-connect/amazon-connect-chat-ui-examples#69]
Hi,

We are facing with following issue in following scenario:

1. When we are using "**customChatWidget**" option, 
2.  and if Agent doesnt reply in time (misses call), 
3. 3. and after missing call agent clicks on "**Close contact**" button, 
4.  and Agent **Accepts** next call on time, 
5. but, a second call is also triggered on Agent Side, and on Agent Side, 1st accepted chat seems to be active, but not actually. That is a weird User Experience, and confuses Agent Side, because it seems as if Agent connected to Client, but not actually.

In above conditions, **sometimes that bug doesnt appear, but usually appears**. Could you please advice a solution?

Thanks

**Comment by angieyu** [comment]
Hi, what is your use case for this? Did you know that chat is available in the product now? https://docs.aws.amazon.com/connect/latest/adminguide/add-chat-to-website.html

**Comment by angieyu** [comment]
Hi @komnatadeveloper I was able to reproduce the issue. I'll ask around if people are aware of a fix. The original maintainer for this is no longer on the team and the example is pretty old. I'll keep you updated on what I find.

**Comment by spencerlepine** [comment]
Hi @komnatadeveloper,

If this issue is still reproducible, please attach a screen recording or screenshot with detailed steps to reproduce.

I am going to resolve this issue due to inactivity, please feel free to re-open or reach out if there are further updates.

Thanks,
Spencer

---

I am not able to reproduce this issue. There have been many updates to the open source [AmazonConnectChatInterface](https://github.com/amazon-connect/amazon-connect-chat-interface) and [ChatJS](https://github.com/amazon-connect/amazon-connect-chatjs) code since this issue was raised. Can you confirm that you are able to reproduce with the latest [`customChatWidget`](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/customChatWidget) code?

There may have been some update to the Agent UI (CCP) since release. I am not able to accept another call until I have **cleared** the missed call.

https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/60903378/82278378-c601-4e75-86a5-799c6f7dccce


<img width="325" alt="Screenshot 2023-09-27 at 4 29 33 PM" src="https://github.com/amazon-connect/amazon-connect-chat-ui-examples/assets/60903378/4df06535-eab0-45a1-be80-a5f7dddfc266">
