### ISSUE TITLE
Cors errors occured when we created request to  'https://participant.connect.us-west-2.amazonaws.com/participant/connection' 

### ISSUE THREAD

**Issue by Karthik-Bahiradhan** [amazon-connect/amazon-connect-chat-ui-examples#7]
We are trying to execute the example chat application with lambda & API Gateway,

We are able to get the response from API Gateway, but when we tried to create the request, we are getting following errors as below,

Access to XMLHttpRequest at 'https://participant.connect.us-west-2.amazonaws.com/participant/connection' from origin 'https://amazonconnectchat.s3.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Could you please help on this issue.

**Comment by efh365** [comment]
Hi Karthik,

Are you testing the asyncCustomerChatUX solution or the startChatContactAPI? If you are testing the async one with the UX, you should be making calls from the CloudFront distribution, not from the S3 location.

**Comment by ashokdevlabs** [comment]
Hello, We are trying to add asyncCustomerChatUX chat to a custom website and facing the above CORS issues. If you suggest any solution for this so that would be helpful. As part of adding chat widget to custom website i have done below things.
1. I have added website Url to initiateChatLambda function
2. We have created S3 bucket to host static website and imported 'amazon-connect-chat-interface.js'

Could you please help on this issue.
