### ISSUE TITLE
asyncCustomChatUX----After Click End Chat Button Screen Requires Refreshing otherwise chat initialiazation failed

### ISSUE THREAD

**Issue by gonovanatasha** [amazon-connect/amazon-connect-chat-ui-examples#70]
After deploying asyncCustomChatUX  Cf . Everything is fine but whenever i ended chat and reopen chat it shows initialization failed until i do page refresh. What i found is if dynamodb is not updated with s3 key it will show initialization failed error as it passes same params thinking that chat is not ended

**Comment by angieyu** [comment]
Hi, can you try initiating chat with a different username? You also need to click "end chat", rather than just closing the chat window, to update the DynamoDB entry that the chat is closed.

**Comment by gonovanatasha** [comment]
@angieyu i clicked on "end chat" everythime but dynamodb updates late and when we click icon again it shows initialization failed

**Comment by jobijaco** [comment]
Hi @angieyu,
I am facing a similar issue when trying to initialize the Chat widget on the customer application end. The DynamoDb table does not get updated when a new chat is initiated after ending the previous chat. This makes use of the same Participant token leading to a 403 Access Denied error.

Attaching the .har file for reference.

Please let me know on how to proceed further on this?

**Comment by jobijaco** [comment]
HAR file of the Chat Widget initiatization

**Comment by haomingli2020** [comment]
Hi, on Feb 10, 2023 the [asyncCustomerChatUX](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/asyncCustomerChatUX) template was deprecated.
Please switch to using the [startChatContactAPI](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/startChatContactAPI) template, and let us know if this issue still occurs

**Comment by spencerlepine** [comment]
Resolving, due to team no longer supporting [asyncCustomerChatUX](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/asyncCustomerChatUX) example - will not fix.

Please refer to [startChatContactAPI](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/startChatContactAPI) solution with Persistent chat feature: 

> how do we recover an ongoing session? So, if the user leaves the window and comes back, can we get into the same chat window if the session is still active?

You need to maintain the chat contact id (initial/segment contact) per use-case and supply it when starting a new persistent chat session via `StartChatContact` api. Ensure that the past chat is ended, as in the given example, when the user leaves the chat session, they must end that chat, either via DisconnectParticipant or StopChat.

> and for sessions that are closed, in the API there is this persistent chat attributes

Persistent chat requires customers to enable chat transcript on the instance. (please check Data Storage section [here](https://docs.aws.amazon.com/connect/latest/adminguide/update-instance-settings.html)). We load transcript on-demand, what that means is that customers must call the `GetTranscript` api to see past chat transcript via the pagination token. (How to access past chat contact transcript for a persistent chat [here](https://docs.aws.amazon.com/connect/latest/adminguide/chat-persistence.html))

Thanks,
Spencer

**Comment by outplex** [comment]
> Resolving, due to team no longer supporting [asyncCustomerChatUX](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/asyncCustomerChatUX) example - will not fix.
> 
> Please refer to [startChatContactAPI](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/startChatContactAPI) solution with Persistent chat feature:
> 
> > how do we recover an ongoing session? So, if the user leaves the window and comes back, can we get into the same chat window if the session is still active?
> 
> You need to maintain the chat contact id (initial/segment contact) per use-case and supply it when starting a new persistent chat session via `StartChatContact` api. Ensure that the past chat is ended, as in the given example, when the user leaves the chat session, they must end that chat, either via DisconnectParticipant or StopChat.
> 
> > and for sessions that are closed, in the API there is this persistent chat attributes
> 
> Persistent chat requires customers to enable chat transcript on the instance. (please check Data Storage section [here](https://docs.aws.amazon.com/connect/latest/adminguide/update-instance-settings.html)). We load transcript on-demand, what that means is that customers must call the `GetTranscript` api to see past chat transcript via the pagination token. (How to access past chat contact transcript for a persistent chat [here](https://docs.aws.amazon.com/connect/latest/adminguide/chat-persistence.html))
> 
> Thanks, Spencer

@spencerlepine thanks, quick question. This solution you're sharing allows us to load a previous conversation's transcript when starting a new chat. But how could we connect a participant to the same chat conversation if let's say the participant refreshes the page or browses to a different site section.
