### ISSUE TITLE
Editing Toolbar with input textfield of chat message  in Amazon Connect Custom Widget 

### ISSUE THREAD

**Issue by gonovanatasha** [amazon-connect/amazon-connect-chat-ui-examples#77]
![image](https://user-images.githubusercontent.com/71895144/201167159-09467835-63ca-40f8-8355-38194023cc60.png)

As it is visible in first screenshot that chat widget given by Amazon Connect CCP script has editing functionality and send button within input field but custom chat widget solution neither have editing functionality and send button within input field.

**Comment by xiajon-amzn** [comment]
Could you share more details on this issue? Were there any console errors and did you make any changes to the example code? Could you give steps to reproduce this issue? The toolbar is expected to show when rich messaging is enabled and the send button is expected to be visible at all times.

**Comment by haomingli2020** [comment]
Hi @gonovanatasha 
The custom chat widget solution provided in this repo should have the send message button now. 
But I'm not sure I understand the editing functionality, do you mean the rich formatting capabilities (bold, italics, hyperlink, etc.)? If so they are also supported today and you can follow the steps [here](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/customChatWidget#enabling-rich-messaging) to enable it

**Comment by spencerlepine** [comment]
Hi @gonovanatasha, 

It appears when this issue was raised, the Custom Chat Widget example solution was not updated with the new rich toolbar feature. However, this was added in #88.

If you are looking to implement the rich toolbar in the Custom Widget solution yourself, you can refer to this pull request for example changes: https://github.com/amazon-connect/amazon-connect-chat-interface/pull/92

Also, please refer to this documentation for enabling the feature for your instance/widget:
- https://github.com/amazon-connect/amazon-connect-chat-interface/blob/spenlep/improve-readme-documentation/.github/docs/RichTextFormattingFeature.md
- https://docs.aws.amazon.com/connect/latest/adminguide/enable-text-formatting-chat.html

Resolving this issue. Please feel free to reach out with any further questions

Thanks,
Spencer
