### ISSUE TITLE
Question regarding React Native

### ISSUE THREAD

**Issue by aprifti-wr** [amazon-connect/amazon-connect-chat-ui-examples#99]
Hey team,

I m sorry if this is not the right place to ask.

Is there any react-native implementation for amazon connect chat?

if not what options do we have?

**Comment by spencerlepine** [comment]
Hi @aprifti-wr,

Currently, ChatJS does not work in React Native applications due to websocket issues.

Team has not yet released a mobile chat example here, and is tracking this blocking issue: https://github.com/amazon-connect/amazon-connect-chatjs/issues/42 .

Alternative mobile chat solutions use [`WebView`](https://github.com/react-native-webview/react-native-webview), or build with the [`aws-sdk`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-connect/index.html) directly.

Thanks,
Spencer

**Comment by aprifti-wr** [comment]
Hi @spencerlepine 

Thank you for your answer.

**Comment by spencerlepine** [comment]
Hi @aprifti-wr 

Reaching out with update - Team has released a React Native + ChatJS [Expo demo application](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/connectReactNativeChat). 

This can be referenced to implement basic functionality creating a chat session and sending messages.

The `amazon-connect-chatjs@^1.5.0` release included updates to `WebSocketManager` to unblock existing issue [[ref](https://github.com/amazon-connect/amazon-connect-chatjs/issues/42)].

Team will continue to track issues/discussions for React Native in this ui-examples repository. Feel free to reopen/reach out with any further questions.

Thanks,
Spencer

**Comment by aprifti-wr** [comment]
Hi Spencer, thank you very much. 

We have been notified and we have already started the evaluation of chatjs.
